version: '3.7'

services:
  client:
    restart: always
    build: 
      context: ./cliente
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:3000"
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=marihuana
  redis:
    image: redis
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379